# Generated by Django 4.0.4 on 2022-05-03 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('auditmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.auditmodel')),
                ('location_from', models.CharField(max_length=200, verbose_name='De')),
                ('location_to', models.CharField(max_length=200, verbose_name='Para')),
                ('initial_value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor inicial')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Quantidade')),
                ('amount_type', models.CharField(choices=[('TON', 'Toneladas'), ('KG', 'Kilos')], max_length=3, verbose_name='Tipo')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='users.person', verbose_name='Ofertante')),
            ],
            bases=('base.auditmodel',),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Quantidade')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.offer', verbose_name='Ofertante')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='users.person', verbose_name='Fornecedor')),
            ],
        ),
    ]
