# Generated by Django 4.0.4 on 2022-05-03 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('auditmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.auditmodel')),
                ('name', models.CharField(max_length=128, verbose_name='Nome')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Sobre')),
                ('doc', models.CharField(max_length=18, unique=True, verbose_name='Documento de Identificação')),
                ('active', models.BooleanField(default=False, verbose_name='Ativo ?')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Site')),
            ],
            options={
                'unique_together': {('name', 'doc')},
            },
            bases=('base.auditmodel',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.person')),
            ],
            bases=('users.person',),
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.person')),
            ],
            bases=('users.person',),
        ),
    ]
